export default function Tools() {
	const tFull = tAlias({ context: "full" });

	return (
		<div className="container">
			<SettingsPageControl style={{ marginBlockEnd: "4px" }}>{t.descriptions.tools}</SettingsPageControl>
			<SettingsCard
				title={tFull.titles.flow}
				details={t.descriptions.tools.flow}
				type="button"
				icon="curve"
			/>
			<SettingsCard
				title={tFull.titles.selector}
				details={t.descriptions.tools.selector}
				type="button"
				icon="search"
			/>
			<SettingsCard
				title={tFull.titles.replacer}
				details={t.descriptions.tools.replacer}
				type="button"
				icon="replace"
				selectInfo={t(11).selectInfo.trackEvent}
				selectValid={0}
			/>
			<SettingsCard
				title={tFull.titles.propertizer}
				details={t.descriptions.tools.propertizer}
				type="button"
				icon="wrench_multiple"
				selectInfo={t(1).selectInfo.trackEvent}
				selectValid={1}
			/>
			<SettingsCard
				title={tFull.titles.subtitles}
				details={t.descriptions.tools.subtitles}
				type="button"
				icon="subtitles"
				selectInfo={t(1).selectInfo.audioEvent}
				selectValid={1}
			/>
			<SettingsCard
				title={tFull.titles.effector}
				details={t.descriptions.tools.effector}
				type="button"
				icon="sparkle"
				selectInfo={t(1).selectInfo.videoEvent}
				selectValid={1}
			/>
			<SettingsCard
				title={tFull.titles.fader}
				details={t.descriptions.tools.fader}
				type="button"
				icon="fade"
				selectInfo={t(1).selectInfo.trackEvent}
				selectValid={1}
			/>
			<SettingsCard
				title={tFull.titles.exportScore}
				details={t.descriptions.tools.exportScore}
				type="button"
				icon="score_forward"
			/>

			<Subheader>{t.tools.converters}</Subheader>
			<SettingsCard
				title={t.stream.tuning.tuningMethod}
				details={t.descriptions.tools.converters.tuningMethod}
				type="button"
				icon="tuning"
				selectInfo={t(1).selectInfo.videoEvent}
				selectValid={1}
			/>
			<SettingsCard
				title={t.stream.transformMethod}
				details={t.descriptions.tools.converters.transformMethod}
				type="button"
				icon="zoom_fit"
				selectInfo={t(1).selectInfo.videoEvent}
				selectValid={1}
			/>
			<SettingsCard
				title={tFull.titles.clawer}
				details={t.descriptions.tools.converters.clawer}
				type="button"
				icon="claw_machine"
				selectInfo={t(1).selectInfo.audioEventOnlyOne}
				selectValid={1}
			/>

			<Subheader>{t.tools.services}</Subheader>
			<SettingsCard
				title={tFull.titles.variableTempo}
				details={t.descriptions.tools.variableTempo}
				type="button"
				icon="speed_play"
			/>
			<SettingsCard
				title={tFull.titles.ultraPaste}
				details={t.descriptions.tools.ultraPaste}
				type="button"
				icon="clipboard_star"
			/>
		</div>
	);
}
