export default function Tools() {
	return (
		<div className="container">
			<SettingsPageControl style={{ marginBlockEnd: "4px" }}>{t.descriptions.tools}</SettingsPageControl>
			<SettingsCard
				title={t.tools.flow}
				details={t.descriptions.tools.flow}
				type="button"
				icon="flow"
			/>
			<SettingsCard
				title={t.tools.selectorAndReplacer}
				details={t.descriptions.tools.selectorAndReplacer}
				type="button"
				icon="search"
				selectInfo={t(0).selectInfo.trackEvent}
				selectValid={0}
			/>
			<SettingsCard
				title={t.tools.normalizer}
				details={t.descriptions.tools.normalizer}
				type="button"
				icon="spatial_volume"
				trailingIcon="open"
				selectInfo={t(1).selectInfo.audioEvent} selectValid={1}
			/>
			<SettingsCard
				title={t.tools.subtitles}
				details={t.descriptions.tools.subtitles}
				type="button"
				icon="subtitles"
				selectInfo={t(1).selectInfo.audioEvent}
				selectValid={1}
			/>
			<SettingsCard
				title={t.tools.effector}
				details={t.descriptions.tools.effector}
				type="button"
				icon="sparkle"
				selectInfo={t(1).selectInfo.videoEvent}
				selectValid={1}
			/>
			<SettingsCard
				title={t.tools.fader}
				details={t.descriptions.tools.fader}
				type="button"
				icon="fade"
				selectInfo={t(1).selectInfo.trackEvent}
				selectValid={1}
			/>
			<SettingsCard
				title={t.tools.exportScore}
				details={t.descriptions.tools.exportScore}
				type="button"
				icon="export_score"
			/>

			<Subheader>{t.tools.converters}</Subheader>
			<SettingsCard
				title={t.stream.tuning.tuningMethod}
				details={t.descriptions.tools.converters.tuningMethod}
				type="button"
				icon="tuning"
				selectInfo={t(1).selectInfo.videoEvent}
				selectValid={1}
			/>
			<SettingsCard
				title={t.stream.transformMethod}
				details={t.descriptions.tools.converters.transformMethod}
				type="button"
				icon="zoom_fit"
				selectInfo={t(1).selectInfo.videoEvent}
				selectValid={1}
			/>
			<SettingsCard
				title={t.tools.clawMachine}
				details={t.descriptions.tools.converters.clawMachine}
				type="button"
				icon="claw_machine"
				selectInfo={t(1).selectInfo.audioEventOnlyOne} selectValid={1 === 1}
			/>
		</div>
	);
}
