
//------------------------------------------------------------------------------
// <auto-generated>
// This code is auto generated by the T4 template.
//
// Changes to this file may result in incorrect behavior, and these changes will
// be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace OtomadHelper.WPF.Controls;

public enum DeclaredIcon {
	None,
	Info,
	Warning,
	Error,
	Question,
	Locale,
	Color,
	ExpanderChevronDown,
	CaretUp,
	CaretDown,
	Undo,
	Redo,
	Cut,
	Copy,
	Paste,
	Clear,
	ClearAll,
	SelectAll,
	EyeDropper,
	Delete,
	ChevronUp,
	ChevronDown,
	ChevronLeft,
	ChevronRight,
	ChevronDoubleUp,
	ChevronDoubleDown,
	ChevronDoubleLeft,
	ChevronDoubleRight,
	ChevronUpToLine,
	ChevronDownToLine,
	ChevronLeftToLine,
	ChevronRightToLine,
	ChevronVerticalScrollHere,
	ChevronHorizontalScrollHere,
	VegasPro,
	GitHub,
	ArrowDownload,
	WrenchScrewdriver,
	TextEdit,
	ArrowReset,
	ChevronUp12,
	ChevronDown12,
	TableSimpleInclude,
	Rename,
	InvertColor,
}
