
//------------------------------------------------------------------------------
// <auto-generated>
// This code is auto generated by the T4 template.
//
// Changes to this file may result in incorrect behavior, and these changes will
// be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtomadHelper.Helpers;

public static partial class MathEx {
	extension(Math) {
		public static int FloorMod(int x, int y) {
			int result = x % y;
			if (result != 0 && x < 0 != y < 0)
				result += y;
			return result;
		}
		public static long FloorMod(int x, uint y) {
			long result = x % y;
			if (result != 0 && x < 0 != y < 0)
				result += y;
			return result;
		}
		public static long FloorMod(int x, long y) {
			long result = x % y;
			if (result != 0 && x < 0 != y < 0)
				result += y;
			return result;
		}
		public static float FloorMod(int x, float y) {
			float result = x % y;
			if (result != 0 && x < 0 != y < 0)
				result += y;
			return result;
		}
		public static double FloorMod(int x, double y) {
			double result = x % y;
			if (result != 0 && x < 0 != y < 0)
				result += y;
			return result;
		}
		public static decimal FloorMod(int x, decimal y) {
			decimal result = x % y;
			if (result != 0 && x < 0 != y < 0)
				result += y;
			return result;
		}
		public static long FloorMod(uint x, int y) {
			long result = x % y;
			if (result != 0 && x < 0 != y < 0)
				result += y;
			return result;
		}
		public static uint FloorMod(uint x, uint y) {
			uint result = x % y;
			if (result != 0 && x < 0 != y < 0)
				result += y;
			return result;
		}
		public static long FloorMod(uint x, long y) {
			long result = x % y;
			if (result != 0 && x < 0 != y < 0)
				result += y;
			return result;
		}
		public static ulong FloorMod(uint x, ulong y) {
			ulong result = x % y;
			if (result != 0 && x < 0 != y < 0)
				result += y;
			return result;
		}
		public static float FloorMod(uint x, float y) {
			float result = x % y;
			if (result != 0 && x < 0 != y < 0)
				result += y;
			return result;
		}
		public static double FloorMod(uint x, double y) {
			double result = x % y;
			if (result != 0 && x < 0 != y < 0)
				result += y;
			return result;
		}
		public static decimal FloorMod(uint x, decimal y) {
			decimal result = x % y;
			if (result != 0 && x < 0 != y < 0)
				result += y;
			return result;
		}
		public static long FloorMod(long x, int y) {
			long result = x % y;
			if (result != 0 && x < 0 != y < 0)
				result += y;
			return result;
		}
		public static long FloorMod(long x, uint y) {
			long result = x % y;
			if (result != 0 && x < 0 != y < 0)
				result += y;
			return result;
		}
		public static long FloorMod(long x, long y) {
			long result = x % y;
			if (result != 0 && x < 0 != y < 0)
				result += y;
			return result;
		}
		public static float FloorMod(long x, float y) {
			float result = x % y;
			if (result != 0 && x < 0 != y < 0)
				result += y;
			return result;
		}
		public static double FloorMod(long x, double y) {
			double result = x % y;
			if (result != 0 && x < 0 != y < 0)
				result += y;
			return result;
		}
		public static decimal FloorMod(long x, decimal y) {
			decimal result = x % y;
			if (result != 0 && x < 0 != y < 0)
				result += y;
			return result;
		}
		public static ulong FloorMod(ulong x, uint y) {
			ulong result = x % y;
			if (result != 0 && x < 0 != y < 0)
				result += y;
			return result;
		}
		public static ulong FloorMod(ulong x, ulong y) {
			ulong result = x % y;
			if (result != 0 && x < 0 != y < 0)
				result += y;
			return result;
		}
		public static float FloorMod(ulong x, float y) {
			float result = x % y;
			if (result != 0 && x < 0 != y < 0)
				result += y;
			return result;
		}
		public static double FloorMod(ulong x, double y) {
			double result = x % y;
			if (result != 0 && x < 0 != y < 0)
				result += y;
			return result;
		}
		public static decimal FloorMod(ulong x, decimal y) {
			decimal result = x % y;
			if (result != 0 && x < 0 != y < 0)
				result += y;
			return result;
		}
		public static float FloorMod(float x, int y) {
			float result = x % y;
			if (result != 0 && x < 0 != y < 0)
				result += y;
			return result;
		}
		public static float FloorMod(float x, uint y) {
			float result = x % y;
			if (result != 0 && x < 0 != y < 0)
				result += y;
			return result;
		}
		public static float FloorMod(float x, long y) {
			float result = x % y;
			if (result != 0 && x < 0 != y < 0)
				result += y;
			return result;
		}
		public static float FloorMod(float x, ulong y) {
			float result = x % y;
			if (result != 0 && x < 0 != y < 0)
				result += y;
			return result;
		}
		public static float FloorMod(float x, float y) {
			float result = x % y;
			if (result != 0 && x < 0 != y < 0)
				result += y;
			return result;
		}
		public static double FloorMod(float x, double y) {
			double result = x % y;
			if (result != 0 && x < 0 != y < 0)
				result += y;
			return result;
		}
		public static double FloorMod(double x, int y) {
			double result = x % y;
			if (result != 0 && x < 0 != y < 0)
				result += y;
			return result;
		}
		public static double FloorMod(double x, uint y) {
			double result = x % y;
			if (result != 0 && x < 0 != y < 0)
				result += y;
			return result;
		}
		public static double FloorMod(double x, long y) {
			double result = x % y;
			if (result != 0 && x < 0 != y < 0)
				result += y;
			return result;
		}
		public static double FloorMod(double x, ulong y) {
			double result = x % y;
			if (result != 0 && x < 0 != y < 0)
				result += y;
			return result;
		}
		public static double FloorMod(double x, float y) {
			double result = x % y;
			if (result != 0 && x < 0 != y < 0)
				result += y;
			return result;
		}
		public static double FloorMod(double x, double y) {
			double result = x % y;
			if (result != 0 && x < 0 != y < 0)
				result += y;
			return result;
		}
		public static decimal FloorMod(decimal x, int y) {
			decimal result = x % y;
			if (result != 0 && x < 0 != y < 0)
				result += y;
			return result;
		}
		public static decimal FloorMod(decimal x, uint y) {
			decimal result = x % y;
			if (result != 0 && x < 0 != y < 0)
				result += y;
			return result;
		}
		public static decimal FloorMod(decimal x, long y) {
			decimal result = x % y;
			if (result != 0 && x < 0 != y < 0)
				result += y;
			return result;
		}
		public static decimal FloorMod(decimal x, ulong y) {
			decimal result = x % y;
			if (result != 0 && x < 0 != y < 0)
				result += y;
			return result;
		}
		public static decimal FloorMod(decimal x, decimal y) {
			decimal result = x % y;
			if (result != 0 && x < 0 != y < 0)
				result += y;
			return result;
		}
	}
}
