version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
import: []
language: en,vi
words:
  - ani
  - apng
  - appcache
  - automator
  - beziér
  - bouncized
  - ccw
  - composables
  - cooldown
  - cqh
  - cqw
  - cw
  - datamix
  - datamixing
  - datamosh
  - datamoshes
  - datamoshing
  - demibold
  - dvh
  - dvw
  - endregion
  - extralight
  - geq
  - hta
  - immer
  - kbd
  - keyframes
  - lotties
  - ltr
  - mht
  - mhtml
  - miscz
  - moz
  - multilayering
  - multisource
  - multitrack
  - neutual
  - numberish
  - ofx
  - otf
  - otomad
  - otomads
  - pangu
  - partialize
  - pingpong
  - portato
  - prelisten
  - prerenders
  - prve
  - pv
  - quarternary
  - resx
  - rtl
  - segoe
  - shupelunker
  - spherize
  - styl
  - stylelint
  - subclips
  - subheaders
  - svgr
  - tsc
  - ttc
  - tts
  - ultrabold
  - unhover
  - unplugin
  - ust
  - utau
  - vite
  - vnd
  - vocaloid
  - vsq
  - vtt
  - wj
  - xmp
  - ytp
  - ytpmv
  - zustand
ignoreWords:
  - ranne
  - chaosinism
  - grantwoolard
  - cyahega
  - qo
  - zh
  - fcp
  - fc
  - tgs
  - ᵗ
  - ᵗsin
flagWords:
  - colour -> color
  - canot -> cannot
  - cancelled -> canceled
  - tunning -> tuning
  - seting -> setting
  - od -> of
  - draging -> dragging
  - splited -> splitted
  - pesudo -> pseudo
  - exitting -> exiting
  - trailling -> trailing
  - condif -> config
