version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
import: []
language: en,vi
words:
  - ack
  - ani
  - apng
  - appcache
  - automator
  - beziér
  - booleanish
  - bouncized
  - ccw
  - classname
  - classnames
  - composables
  - contenteditable
  - cooldown
  - cqh
  - cqw
  - cw
  - danmaku
  - datamix
  - datamixing
  - datamosh
  - datamoshes
  - datamoshing
  - demibold
  - dvh
  - dvw
  - élastique
  - ele
  - endregion
  - esbuild
  - extralight
  - flyouts
  - geq
  - glsl
  - highp
  - hta
  - immer
  - jsdoc
  - jsdocs
  - kbd
  - keyframes
  - languagedetector
  - lengthenable
  - lengthenings
  - lightningcss
  - lotties
  - ltr
  - mht
  - mhtml
  - miscz
  - mograph
  - mographs
  - moz
  - multilayering
  - multisource
  - multitrack
  - neutual
  - numberish
  - nums
  - ofx
  - otf
  - otomad
  - otomads
  - overrider
  - oversaturation
  - pangu
  - parameterless
  - partialize
  - pingpong
  - pixi
  - portato
  - prelisten
  - prerenders
  - proxied
  - prve
  - pv
  - quarternary
  - resw
  - resx
  - rtl
  - segoe
  - shupelunker
  - spherize
  - styl
  - stylelint
  - subclips
  - subgrid
  - subgrids
  - subheaders
  - svgr
  - timecode
  - timecodes
  - tsc
  - ttc
  - tts
  - ultrabold
  - unhover
  - unplugin
  - unsmooth
  - upsize
  - ust
  - utau
  - valtio
  - vite
  - vnd
  - vocaloid
  - vsq
  - vtt
  - webgl
  - wj
  - xmlbuilder
  - xmp
  - yoooo
  - ytp
  - ytpmv
  - zustand
ignoreWords:
  - ranne
  - chaosinism
  - grantwoolard
  - cyahega
  - motosai
  - qo
  - zh
  - fcp
  - fc
  - tgs
  - ᵗ
  - ᵗsin
  - pn
flagWords:
  - colour -> color
  - canot -> cannot
  - cancelled -> canceled
  - tunning -> tuning
  - seting -> setting
  - od -> of
  - draging -> dragging
  - splited -> splitted
  - pesudo -> pseudo
  - exitting -> exiting
  - trailling -> trailing
  - condif -> config
  - comflict -> conflict
  - typoef -> typeof
  - grey -> gray
