version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
import: []
language: en,vi
words:
  - ani
  - automator
  - beziér
  - composables
  - datamix
  - datamixing
  - datamosh
  - datamoshes
  - datamoshing
  - geq
  - immer
  - keyframes
  - lotties
  - miscz
  - multilayering
  - multisource
  - multitrack
  - neutual
  - ofx
  - otomad
  - otomads
  - partialize
  - portato
  - prelisten
  - prerenders
  - prve
  - pv
  - quarternary
  - shupelunker
  - subclips
  - subheaders
  - tts
  - unhover
  - ust
  - utau
  - vocaloid
  - vsq
  - wj
  - ytp
  - ytpmv
  - zustand
ignoreWords:
  - ranne
  - chaosinism
  - grantwoolard
  - cyahega
  - qo
  - zh
  - fcp
  - fc
  - endregion
  - moz
  - tgs
  - dvw
  - dvh
flagWords:
  - colour -> color
  - canot -> cannot
  - cancelled -> canceled
  - tunning -> tuning
  - seting -> setting
  - od -> of
