
//------------------------------------------------------------------------------
// <auto-generated>
// This code is auto generated by the T4 template.
//
// Changes to this file may result in incorrect behavior, and these changes will
// be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace OtomadHelper.Helpers.LocalizeGen;

public class Root(Localize localize, string ancestor = "") : LocalizeNested(localize, ancestor) {
	public Host Host { get { if (field is null) field = new(localize, "Host"); return field; } }
	public Window Window { get { if (field is null) field = new(localize, "Window"); return field; } }
	public ContentDialog ContentDialog { get { if (field is null) field = new(localize, "ContentDialog"); return field; } }
	public WrongOpeningMethod WrongOpeningMethod { get { if (field is null) field = new(localize, "WrongOpeningMethod"); return field; } }
	public TextBox TextBox { get { if (field is null) field = new(localize, "TextBox"); return field; } }
	public ColorPicker ColorPicker { get { if (field is null) field = new(localize, "ColorPicker"); return field; } }
	public QuickSelectIntervalEditor QuickSelectIntervalEditor { get { if (field is null) field = new(localize, "QuickSelectIntervalEditor"); return field; } }
	public Flyout Flyout { get { if (field is null) field = new(localize, "Flyout"); return field; } }
	public Keybindings Keybindings { get { if (field is null) field = new(localize, "Keybindings"); return field; } }
	public Descriptions Descriptions { get { if (field is null) field = new(localize, "Descriptions"); return field; } }
	public ResetConfig ResetConfig { get { if (field is null) field = new(localize, "ResetConfig"); return field; } }
	public SplashOverflowMenu SplashOverflowMenu { get { if (field is null) field = new(localize, "SplashOverflowMenu"); return field; } }
	public Shared Shared { get { if (field is null) field = new(localize, "Shared"); return field; } }
}
public class Host(Localize localize, string ancestor = "") : LocalizeNested(localize, ancestor) {
	public Host_ToolTip ToolTip { get { if (field is null) field = new(localize, "Host.ToolTip"); return field; } }
}
public class Host_ToolTip(Localize localize, string ancestor = "") : LocalizeNested(localize, ancestor) {
	/// <summary>
	/// Import %1
	/// </summary>
	public string ImportToHere => base.GetString("Host.ToolTip.ImportToHere");
}
public class Window(Localize localize, string ancestor = "") : LocalizeNested(localize, ancestor) {
	/// <summary>
	/// Minimize
	/// </summary>
	public string Minimize => base.GetString("Window.Minimize");
	/// <summary>
	/// Maximize
	/// </summary>
	public string Maximize => base.GetString("Window.Maximize");
	/// <summary>
	/// Restore
	/// </summary>
	public string Restore => base.GetString("Window.Restore");
	/// <summary>
	/// Close
	/// </summary>
	public string Close => base.GetString("Window.Close");
}
public class ContentDialog(Localize localize, string ancestor = "") : LocalizeNested(localize, ancestor) {
	public ContentDialog_Button Button { get { if (field is null) field = new(localize, "ContentDialog.Button"); return field; } }
	public ContentDialog_Expander Expander { get { if (field is null) field = new(localize, "ContentDialog.Expander"); return field; } }
	public ContentDialog_ShowError ShowError { get { if (field is null) field = new(localize, "ContentDialog.ShowError"); return field; } }
}
public class ContentDialog_Button(Localize localize, string ancestor = "") : LocalizeNested(localize, ancestor) {
	/// <summary>
	/// <u>O</u>K
	/// </summary>
	public string Ok => base.GetString("ContentDialog.Button.Ok");
	/// <summary>
	/// <u>C</u>ancel
	/// </summary>
	public string Cancel => base.GetString("ContentDialog.Button.Cancel");
	/// <summary>
	/// <u>C</u>lose
	/// </summary>
	public string Close => base.GetString("ContentDialog.Button.Close");
	/// <summary>
	/// <u>L</u>earn more
	/// </summary>
	public string LearnMore => base.GetString("ContentDialog.Button.LearnMore");
	/// <summary>
	/// Loca<u>t</u>e
	/// </summary>
	public string Locate => base.GetString("ContentDialog.Button.Locate");
	/// <summary>
	/// Copy <u>m</u>essage
	/// </summary>
	public string CopyMessage => base.GetString("ContentDialog.Button.CopyMessage");
	/// <summary>
	/// Copied!
	/// </summary>
	public string Copied => base.GetString("ContentDialog.Button.Copied");
	/// <summary>
	/// Revert
	/// </summary>
	public string Revert => base.GetString("ContentDialog.Button.Revert");
}
public class ContentDialog_Expander(Localize localize, string ancestor = "") : LocalizeNested(localize, ancestor) {
	/// <summary>
	/// Expand details
	/// </summary>
	public string ExpandDetails => base.GetString("ContentDialog.Expander.ExpandDetails");
	/// <summary>
	/// Collapse details
	/// </summary>
	public string CollapseDetails => base.GetString("ContentDialog.Expander.CollapseDetails");
}
public class ContentDialog_ShowError(Localize localize, string ancestor = "") : LocalizeNested(localize, ancestor) {
	/// <summary>
	/// Error
	/// </summary>
	public string Title => base.GetString("ContentDialog.ShowError.Title");
	/// <summary>
	/// Error: 
	/// </summary>
	public string WithColon => base.GetString("ContentDialog.ShowError.WithColon");
}
public class WrongOpeningMethod(Localize localize, string ancestor = "") : LocalizeNested(localize, ancestor) {
	public WrongOpeningMethod_Script Script { get { if (field is null) field = new(localize, "WrongOpeningMethod.Script"); return field; } }
}
public class WrongOpeningMethod_Script(Localize localize, string ancestor = "") : LocalizeNested(localize, ancestor) {
	/// <summary>
	/// Hey, you misplaced the extension!
	/// </summary>
	public string Title => base.GetString("WrongOpeningMethod.Script.Title");
	/// <summary>
	/// The new version of Otomad Helper is an extension. Unlike the old version, it is not a script.<br />
	/// <br />
	/// Please move the extension to the Application Extensions directory of VEGAS instead of the Script Menu directory.<br />
	/// <br />
	/// Location:
	/// </summary>
	public string Content => base.GetString("WrongOpeningMethod.Script.Content");
}
public class TextBox(Localize localize, string ancestor = "") : LocalizeNested(localize, ancestor) {
	public TextBox_Menu Menu { get { if (field is null) field = new(localize, "TextBox.Menu"); return field; } }
	public TextBox_NumericUpDown NumericUpDown { get { if (field is null) field = new(localize, "TextBox.NumericUpDown"); return field; } }
}
public class TextBox_Menu(Localize localize, string ancestor = "") : LocalizeNested(localize, ancestor) {
	/// <summary>
	/// Clear All
	/// </summary>
	public string ClearAll => base.GetString("TextBox.Menu.ClearAll");
}
public class TextBox_NumericUpDown(Localize localize, string ancestor = "") : LocalizeNested(localize, ancestor) {
	/// <summary>
	/// Increase
	/// </summary>
	public string Increase => base.GetString("TextBox.NumericUpDown.Increase");
	/// <summary>
	/// Decrease
	/// </summary>
	public string Decrease => base.GetString("TextBox.NumericUpDown.Decrease");
}
public class ColorPicker(Localize localize, string ancestor = "") : LocalizeNested(localize, ancestor) {
	/// <summary>
	/// Select a Color
	/// </summary>
	public string Title => base.GetString("ColorPicker.Title");
	/// <summary>
	/// Eye dropper
	/// </summary>
	public string EyeDropper => base.GetString("ColorPicker.EyeDropper");
	/// <summary>
	/// Invert
	/// </summary>
	public string Invert => base.GetString("ColorPicker.Invert");
	public ColorPicker_Axis Axis { get { if (field is null) field = new(localize, "ColorPicker.Axis"); return field; } }
	public ColorPicker_AxisAbbrs AxisAbbrs { get { if (field is null) field = new(localize, "ColorPicker.AxisAbbrs"); return field; } }
	public ColorPicker_Aria Aria { get { if (field is null) field = new(localize, "ColorPicker.Aria"); return field; } }
}
public class ColorPicker_Axis(Localize localize, string ancestor = "") : LocalizeNested(localize, ancestor) {
	/// <summary>
	/// Red
	/// </summary>
	public string Red => base.GetString("ColorPicker.Axis.Red");
	/// <summary>
	/// Green
	/// </summary>
	public string Green => base.GetString("ColorPicker.Axis.Green");
	/// <summary>
	/// Blue
	/// </summary>
	public string Blue => base.GetString("ColorPicker.Axis.Blue");
	/// <summary>
	/// Hue
	/// </summary>
	public string Hue => base.GetString("ColorPicker.Axis.Hue");
	/// <summary>
	/// Saturation
	/// </summary>
	public string Saturation => base.GetString("ColorPicker.Axis.Saturation");
	/// <summary>
	/// Lightness
	/// </summary>
	public string Lightness => base.GetString("ColorPicker.Axis.Lightness");
	/// <summary>
	/// Brightness
	/// </summary>
	public string Brightness => base.GetString("ColorPicker.Axis.Brightness");
	/// <summary>
	/// White
	/// </summary>
	public string White => base.GetString("ColorPicker.Axis.White");
	/// <summary>
	/// Black
	/// </summary>
	public string Black => base.GetString("ColorPicker.Axis.Black");
	/// <summary>
	/// Cyan
	/// </summary>
	public string Cyan => base.GetString("ColorPicker.Axis.Cyan");
	/// <summary>
	/// Magenta
	/// </summary>
	public string Magenta => base.GetString("ColorPicker.Axis.Magenta");
	/// <summary>
	/// Yellow
	/// </summary>
	public string Yellow => base.GetString("ColorPicker.Axis.Yellow");
	/// <summary>
	/// Key/Black
	/// </summary>
	public string Key => base.GetString("ColorPicker.Axis.Key");
	/// <summary>
	/// Luminance
	/// </summary>
	public string Luminance => base.GetString("ColorPicker.Axis.Luminance");
	/// <summary>
	/// a-Axis (?Green ? +Red)
	/// </summary>
	public string AAxisInLab => base.GetString("ColorPicker.Axis.AAxisInLab");
	/// <summary>
	/// b-Axis (?Blue ? +Yellow)
	/// </summary>
	public string BAxisInLab => base.GetString("ColorPicker.Axis.BAxisInLab");
	/// <summary>
	/// Chroma
	/// </summary>
	public string Chroma => base.GetString("ColorPicker.Axis.Chroma");
	/// <summary>
	/// Alpha/Opacity
	/// </summary>
	public string Alpha => base.GetString("ColorPicker.Axis.Alpha");
	/// <summary>
	/// Hexadecimal
	/// </summary>
	public string Hex => base.GetString("ColorPicker.Axis.Hex");
}
public class ColorPicker_AxisAbbrs(Localize localize, string ancestor = "") : LocalizeNested(localize, ancestor) {
	/// <summary>
	/// R
	/// </summary>
	public string Red => base.GetString("ColorPicker.AxisAbbrs.Red");
	/// <summary>
	/// G
	/// </summary>
	public string Green => base.GetString("ColorPicker.AxisAbbrs.Green");
	/// <summary>
	/// B
	/// </summary>
	public string Blue => base.GetString("ColorPicker.AxisAbbrs.Blue");
	/// <summary>
	/// H
	/// </summary>
	public string Hue => base.GetString("ColorPicker.AxisAbbrs.Hue");
	/// <summary>
	/// S
	/// </summary>
	public string Saturation => base.GetString("ColorPicker.AxisAbbrs.Saturation");
	/// <summary>
	/// L
	/// </summary>
	public string Lightness => base.GetString("ColorPicker.AxisAbbrs.Lightness");
	/// <summary>
	/// B
	/// </summary>
	public string Brightness => base.GetString("ColorPicker.AxisAbbrs.Brightness");
	/// <summary>
	/// W
	/// </summary>
	public string White => base.GetString("ColorPicker.AxisAbbrs.White");
	/// <summary>
	/// B
	/// </summary>
	public string Black => base.GetString("ColorPicker.AxisAbbrs.Black");
	/// <summary>
	/// C
	/// </summary>
	public string Cyan => base.GetString("ColorPicker.AxisAbbrs.Cyan");
	/// <summary>
	/// M
	/// </summary>
	public string Magenta => base.GetString("ColorPicker.AxisAbbrs.Magenta");
	/// <summary>
	/// Y
	/// </summary>
	public string Yellow => base.GetString("ColorPicker.AxisAbbrs.Yellow");
	/// <summary>
	/// K
	/// </summary>
	public string Key => base.GetString("ColorPicker.AxisAbbrs.Key");
	/// <summary>
	/// L
	/// </summary>
	public string Luminance => base.GetString("ColorPicker.AxisAbbrs.Luminance");
	/// <summary>
	/// a
	/// </summary>
	public string AAxisInLab => base.GetString("ColorPicker.AxisAbbrs.AAxisInLab");
	/// <summary>
	/// b
	/// </summary>
	public string BAxisInLab => base.GetString("ColorPicker.AxisAbbrs.BAxisInLab");
	/// <summary>
	/// C
	/// </summary>
	public string Chroma => base.GetString("ColorPicker.AxisAbbrs.Chroma");
	/// <summary>
	/// ¦¡
	/// </summary>
	public string Alpha => base.GetString("ColorPicker.AxisAbbrs.Alpha");
}
public class ColorPicker_Aria(Localize localize, string ancestor = "") : LocalizeNested(localize, ancestor) {
	/// <summary>
	/// Hexadecimal
	/// </summary>
	public string Hex => base.GetString("ColorPicker.Aria.Hex");
	/// <summary>
	/// a-Axis
	/// </summary>
	public string AAxisInLab => base.GetString("ColorPicker.Aria.AAxisInLab");
	/// <summary>
	/// b-Axis
	/// </summary>
	public string BAxisInLab => base.GetString("ColorPicker.Aria.BAxisInLab");
}
public class QuickSelectIntervalEditor(Localize localize, string ancestor = "") : LocalizeNested(localize, ancestor) {
	/// <summary>
	/// Clear
	/// </summary>
	public string Clear => base.GetString("QuickSelectIntervalEditor.Clear");
	/// <summary>
	/// Invert
	/// </summary>
	public string Invert => base.GetString("QuickSelectIntervalEditor.Invert");
	/// <summary>
	/// Rename
	/// </summary>
	public string Rename => base.GetString("QuickSelectIntervalEditor.Rename");
	/// <summary>
	/// Interval
	/// </summary>
	public string Interval => base.GetString("QuickSelectIntervalEditor.Interval");
	/// <summary>
	/// Columns
	/// </summary>
	public string Columns => base.GetString("QuickSelectIntervalEditor.Columns");
	/// <summary>
	/// Rows
	/// </summary>
	public string Rows => base.GetString("QuickSelectIntervalEditor.Rows");
	/// <summary>
	/// Quick Select Interval Editor
	/// </summary>
	public string DefaultTitle => base.GetString("QuickSelectIntervalEditor.DefaultTitle");
}
public class Flyout(Localize localize, string ancestor = "") : LocalizeNested(localize, ancestor) {
	public Flyout_ConfirmDelete ConfirmDelete { get { if (field is null) field = new(localize, "Flyout.ConfirmDelete"); return field; } }
}
public class Flyout_ConfirmDelete(Localize localize, string ancestor = "") : LocalizeNested(localize, ancestor) {
	/// <summary>
	/// Delete?
	/// </summary>
	public string Title => base.GetString("Flyout.ConfirmDelete.Title");
}
public class Keybindings(Localize localize, string ancestor = "") : LocalizeNested(localize, ancestor) {
	public Keybindings_Commands Commands { get { if (field is null) field = new(localize, "Keybindings.Commands"); return field; } }
}
public class Keybindings_Commands(Localize localize, string ancestor = "") : LocalizeNested(localize, ancestor) {
	/// <summary>
	/// Use Track Event as Source
	/// </summary>
	public string UseTrackEventAsSource => base.GetString("Keybindings.Commands.UseTrackEventAsSource");
	/// <summary>
	/// Use Project Media as Source
	/// </summary>
	public string UseProjectMediaAsSource => base.GetString("Keybindings.Commands.UseProjectMediaAsSource");
	/// <summary>
	/// Enable YTP Feature
	/// </summary>
	public string EnableYtp => base.GetString("Keybindings.Commands.EnableYtp");
	/// <summary>
	/// Disable YTP Feature
	/// </summary>
	public string DisableYtp => base.GetString("Keybindings.Commands.DisableYtp");
	/// <summary>
	/// Start Generating
	/// </summary>
	public string StartGenerating => base.GetString("Keybindings.Commands.StartGenerating");
	/// <summary>
	/// Reset All User Configurations
	/// </summary>
	public string Reset => base.GetString("Keybindings.Commands.Reset");
}
public class Descriptions(Localize localize, string ancestor = "") : LocalizeNested(localize, ancestor) {
	public Descriptions_ColorPicker ColorPicker { get { if (field is null) field = new(localize, "Descriptions.ColorPicker"); return field; } }
	public Descriptions_QuickSelectIntervalEditor QuickSelectIntervalEditor { get { if (field is null) field = new(localize, "Descriptions.QuickSelectIntervalEditor"); return field; } }
}
public class Descriptions_ColorPicker(Localize localize, string ancestor = "") : LocalizeNested(localize, ancestor) {
	/// <summary>
	/// Pick a color from the screen
	/// </summary>
	public string EyeDropper => base.GetString("Descriptions.ColorPicker.EyeDropper");
	/// <summary>
	/// Inverts the current color
	/// </summary>
	public string Invert => base.GetString("Descriptions.ColorPicker.Invert");
	/// <summary>
	/// Reverts to the color before setting
	/// </summary>
	public string Revert => base.GetString("Descriptions.ColorPicker.Revert");
	public Descriptions_ColorPicker_Aria Aria { get { if (field is null) field = new(localize, "Descriptions.ColorPicker.Aria"); return field; } }
}
public class Descriptions_ColorPicker_Aria(Localize localize, string ancestor = "") : LocalizeNested(localize, ancestor) {
	/// <summary>
	/// Value range 0 to 255
	/// </summary>
	public string Alpha255 => base.GetString("Descriptions.ColorPicker.Aria.Alpha255");
	/// <summary>
	/// Value range 0 to 100
	/// </summary>
	public string Alpha100 => base.GetString("Descriptions.ColorPicker.Aria.Alpha100");
	/// <summary>
	/// Negative number indicates green, positive number indicates red
	/// </summary>
	public string AAxisInLab => base.GetString("Descriptions.ColorPicker.Aria.AAxisInLab");
	/// <summary>
	/// Negative number indicates blue, positive number indicates yellow
	/// </summary>
	public string BAxisInLab => base.GetString("Descriptions.ColorPicker.Aria.BAxisInLab");
}
public class Descriptions_QuickSelectIntervalEditor(Localize localize, string ancestor = "") : LocalizeNested(localize, ancestor) {
	/// <summary>
	/// Unselects all items
	/// </summary>
	public string Clear => base.GetString("Descriptions.QuickSelectIntervalEditor.Clear");
	/// <summary>
	/// Inverts the current selection
	/// </summary>
	public string Invert => base.GetString("Descriptions.QuickSelectIntervalEditor.Invert");
	/// <summary>
	/// Reverts to the selection before setting
	/// </summary>
	public string Revert => base.GetString("Descriptions.QuickSelectIntervalEditor.Revert");
	public Descriptions_QuickSelectIntervalEditor_Aria Aria { get { if (field is null) field = new(localize, "Descriptions.QuickSelectIntervalEditor.Aria"); return field; } }
}
public class Descriptions_QuickSelectIntervalEditor_Aria(Localize localize, string ancestor = "") : LocalizeNested(localize, ancestor) {
	public Descriptions_QuickSelectIntervalEditor_Aria_OneD OneD { get { if (field is null) field = new(localize, "Descriptions.QuickSelectIntervalEditor.Aria.OneD"); return field; } }
	public Descriptions_QuickSelectIntervalEditor_Aria_TwoD TwoD { get { if (field is null) field = new(localize, "Descriptions.QuickSelectIntervalEditor.Aria.TwoD"); return field; } }
}
public class Descriptions_QuickSelectIntervalEditor_Aria_OneD(Localize localize, string ancestor = "") : LocalizeNested(localize, ancestor) {
	/// <summary>
	/// Item {0}
	/// </summary>
	public string Name => base.GetString("Descriptions.QuickSelectIntervalEditor.Aria.OneD.Name");
	/// <summary>
	/// Of {0}
	/// </summary>
	public string HelpText => base.GetString("Descriptions.QuickSelectIntervalEditor.Aria.OneD.HelpText");
}
public class Descriptions_QuickSelectIntervalEditor_Aria_TwoD(Localize localize, string ancestor = "") : LocalizeNested(localize, ancestor) {
	/// <summary>
	/// Column {0}, row {1}
	/// </summary>
	public string Name => base.GetString("Descriptions.QuickSelectIntervalEditor.Aria.TwoD.Name");
	/// <summary>
	/// Of a {0}-column by {1}-row grid
	/// </summary>
	public string HelpText => base.GetString("Descriptions.QuickSelectIntervalEditor.Aria.TwoD.HelpText");
}
public class ResetConfig(Localize localize, string ancestor = "") : LocalizeNested(localize, ancestor) {
	/// <summary>
	/// Are you sure you want to reset all the user configurations?
	/// </summary>
	public string Title => base.GetString("ResetConfig.Title");
	/// <summary>
	/// It cannot be undone; all your user configuration data will be lost! You don¡¯t need to do this unless you encounter unsolvable problems.
	/// </summary>
	public string Content => base.GetString("ResetConfig.Content");
}
public class SplashOverflowMenu(Localize localize, string ancestor = "") : LocalizeNested(localize, ancestor) {
	/// <summary>
	/// Open GitHub repository
	/// </summary>
	public string RepositoryLink => base.GetString("SplashOverflowMenu.RepositoryLink");
	/// <summary>
	/// Get latest version
	/// </summary>
	public string GetLatestVersion => base.GetString("SplashOverflowMenu.GetLatestVersion");
	/// <summary>
	/// Troubleshooting
	/// </summary>
	public string Troubleshooting => base.GetString("SplashOverflowMenu.Troubleshooting");
	/// <summary>
	/// Feedback
	/// </summary>
	public string Feedback => base.GetString("SplashOverflowMenu.Feedback");
	/// <summary>
	/// Reset all user configurations
	/// </summary>
	public string Reset => base.GetString("SplashOverflowMenu.Reset");
}
public class Shared(Localize localize, string ancestor = "") : LocalizeNested(localize, ancestor) {
	public Shared_Plugins Plugins { get { if (field is null) field = new(localize, "Shared.Plugins"); return field; } }
	public Shared_Exceptions Exceptions { get { if (field is null) field = new(localize, "Shared.Exceptions"); return field; } }
	public Shared_Midi Midi { get { if (field is null) field = new(localize, "Shared.Midi"); return field; } }
}
public class Shared_Plugins(Localize localize, string ancestor = "") : LocalizeNested(localize, ancestor) {
	/// <summary>
	/// Pan/Crop
	/// </summary>
	public string PanCrop => base.GetString("Shared.Plugins.PanCrop");
	/// <summary>
	/// Picture in Picture
	/// </summary>
	public string PictureInPicture => base.GetString("Shared.Plugins.PictureInPicture");
	/// <summary>
	/// TransformOFX
	/// </summary>
	public string TransformOfx => base.GetString("Shared.Plugins.TransformOfx");
	/// <summary>
	/// Swirl
	/// </summary>
	public string Swirl => base.GetString("Shared.Plugins.Swirl");
	/// <summary>
	/// Wave
	/// </summary>
	public string Wave => base.GetString("Shared.Plugins.Wave");
	/// <summary>
	/// TV Simulator
	/// </summary>
	public string TvSimulator => base.GetString("Shared.Plugins.TvSimulator");
	/// <summary>
	/// TV
	/// </summary>
	public string TvSimulatorShort => base.GetString("Shared.Plugins.TvSimulatorShort");
	/// <summary>
	/// Titles & Text
	/// </summary>
	public string TitlesAndText => base.GetString("Shared.Plugins.TitlesAndText");
	/// <summary>
	/// (Legacy) Text
	/// </summary>
	public string LegacyText => base.GetString("Shared.Plugins.LegacyText");
	/// <summary>
	/// ProType Titler
	/// </summary>
	public string ProtypeTitler => base.GetString("Shared.Plugins.ProtypeTitler");
	/// <summary>
	/// Credit Roll
	/// </summary>
	public string CreditRoll => base.GetString("Shared.Plugins.CreditRoll");
}
public class Shared_Exceptions(Localize localize, string ancestor = "") : LocalizeNested(localize, ancestor) {
	/// <summary>
	/// Error: 
	/// </summary>
	public string ErrorHeader => base.GetString("Shared.Exceptions.ErrorHeader");
	/// <summary>
	/// The playback rate cannot be set to 0.<br />
	/// <br />
	/// If you want to achieve a static visual, please enable the ¡°Static visual¡± setting.
	/// </summary>
	public string PlaybackRateCannotBeZero => base.GetString("Shared.Exceptions.PlaybackRateCannotBeZero");
	/// <summary>
	/// The step sequence parameter syntax is invalid.<br />
	/// <br />
	/// Please enter the indexes of each initial step separated by commas as the sequence, where 0 represents the ¡°Normal.¡±
	/// </summary>
	public string PrveStepSequenceSyntaxInvalid => base.GetString("Shared.Exceptions.PrveStepSequenceSyntaxInvalid");
	/// <summary>
	/// In the step sequence parameter, at least an index value exceeds the total number of steps or is negative.
	/// </summary>
	public string PrveStepSequenceOutOfRange => base.GetString("Shared.Exceptions.PrveStepSequenceOutOfRange");
}
public class Shared_Midi(Localize localize, string ancestor = "") : LocalizeNested(localize, ancestor) {
	/// <summary>
	/// Unknown
	/// </summary>
	public string Unknown => base.GetString("Shared.Midi.Unknown");
	public Shared_Midi_Instruments Instruments { get { if (field is null) field = new(localize, "Shared.Midi.Instruments"); return field; } }
	public Shared_Midi_Percussions Percussions { get { if (field is null) field = new(localize, "Shared.Midi.Percussions"); return field; } }
}
public class Shared_Midi_Instruments(Localize localize, string ancestor = "") : LocalizeNested(localize, ancestor) {
}
public class Shared_Midi_Percussions(Localize localize, string ancestor = "") : LocalizeNested(localize, ancestor) {
}

